project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path : "language"


#
# Files configuration
#
files: [
 {
  "source" : "/translate/*.*",
  "translation" : "/translations/%locale%/%original_file_name%",
}
]
