project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN


#
# Files configuration
#
# files: [
#  {
#   "source" : "/translate/*.*",
#   "translation" : "/translations/%locale%/%original_file_name%",
# }
# ]

preserve_hierarchy: true

"files": [
  {
      "source": "/beytok_branch/translate/*.*",                                          #source files filter
      "translation": "/beytok_branch/translations/%two_letters_code%/%original_file_name%"        #where translations are stored
  }
]
