project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN


#
# Files configuration
#
# files: [
#  {
#   "source" : "/translate/*.*",
#   "translation" : "/translations/%locale%/%original_file_name%",
# }
# ]

base_path: "./"
preserve_hierarchy: true

"files": [
  {
      "source": "/translate/*",                                          #source files filter
      "translation": "/translations/%two_letters_code%/**/%original_file_name%"        #where translations are stored
  }
]
