# This is a basic workflow to help you get started with Actions

name: CI beytok branch

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  # This workflow contains a single job called "build"
  synchronize-with-crowdin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    # Runs the Crowdin action command
    - name: crowdin action
      uses: crowdin/github-action@master
      with:
        debug_mode: true

        crowdin_branch_name: l10n-to-crowdin
        pull_request_base_branch_name: l10n-to-crowdin
        localization_branch_name: l10n-from-crowdin
        upload_translations: false
        download_translations: true
        skip_untranslated_strings: false
        export_only_approved: false
        # global options
        config: 'beytok_branch/crowdin.yml'


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
